server:
  port: 80

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
spring:
  application:
    name: gateway-8001
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: cloud-provider-uc
          uri:  lb://cloud-provider-uc
          predicates:
          - Path=/api/auth/**

        - id: cloud-provider-orders
          uri:  lb://cloud-provider-orders
          predicates:
          - Path=/api/order/**,/api/member/**

        - id: cloud-provider-gas
          uri:  lb://cloud-provider-gas
          predicates:
          - Path=/api/**




